12-Ejercicio1/cineapp/cineapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('directores/', include('directores.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

12-Ejercicio1/cineapp/directores/urls.py
from django.urls import path
from .views import lista_directores, detalle_director, peliculas_director

urlpatterns = [
    path('', lista_directores, name='lista_directores'),
    path('<int:director_id>/', detalle_director, name='detalle_director'),
    path('<int:director_id>/peliculas/',
         peliculas_director, name='peliculas_director'),
]

12-Ejercicio1/cineapp/directores/models.py
from django.db import models


class Director(models.Model):
    nombre = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    nacionalidad = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Pelicula(models.Model):
    titulo = models.CharField(max_length=100)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    descripcion = models.TextField()

    def __str__(self):
        return self.titulo

12-Ejercicio1/cineapp/directores/views.py
from django.shortcuts import render, get_object_or_404
from .models import Director, Pelicula


def lista_directores(request):
    directores = Director.objects.all()
    return render(request, 'lista_directores.html', {'directores': directores})


def detalle_director(request, director_id):
    director = get_object_or_404(Director, id=director_id)
    return render(request, 'detalle_director.html', {'director': director})


def peliculas_director(request, director_id):
    director = get_object_or_404(Director, id=director_id)
    peliculas = Pelicula.objects.filter(director=director)
    return render(request, 'directores/peliculas_director.html', {'director': director, 'peliculas': peliculas})

12-Ejercicio1/cineapp/directores/templates/detalle_director.html
<!DOCTYPE html>
<html>
  <head>
    <title>Detalle de Director</title>
  </head>
  <body>
    <h1>{{ director.nombre }}</h1>
    <p>Fecha de Nacimiento: {{ director.fecha_nacimiento }}</p>
    <p>Nacionalidad: {{ director.nacionalidad }}</p>
    <h2>Películas</h2>
    <ul>
      {% for pelicula in director.pelicula_set.all %}
      <li>
        <a href="{% url 'peliculas_director' pelicula.id %}"
          >{{ pelicula.titulo }}</a
        >
      </li>
      {% empty %}
      <li>No hay películas registradas para este director.</li>
      {% endfor %}
    </ul>
  </body>
</html>

12-Ejercicio1/cineapp/directores/templates/lista_directores.html
<!DOCTYPE html>
<html>
  <head>
    <title>Lista de Directores</title>
  </head>
  <body>
    <h1>Lista de Directores</h1>
    <ul>
      {% for director in directores %}
      <li>
        <a href="{% url 'detalle_director' director.id %}"
          >{{ director.nombre }}</a
        >
      </li>
      {% empty %}
      <li>No hay directores registrados.</li>
      {% endfor %}
    </ul>
  </body>
</html>

12-Ejercicio1/cineapp/directores/templates/peliculas_director.html
<!-- detalle_pelicula.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>Detalle de Película</title>
  </head>
  <body>
    <h1>{{ pelicula.titulo }}</h1>
    <p><strong>Director:</strong> {{ pelicula.titulo }}</p>
    <p><strong>Descripción:</strong> {{ pelicula.descripcion }}</p>
    <a href="{% url 'detalle_director' director.id %}"
      >Volver a las películas del director</a
    >
  </body>
</html>